### ISSUE TITLE
找不到 1554G4442 or 1554G4442-8 的法案資訊

### ISSUE THREAD

**Issue by kiang** [g0v/ly.g0v.tw#184]
主要是看到這份關係文書：
http://lci.ly.gov.tw/LyLCEW/agenda1/02/pdf/08/06/16/LCEWA01_080616_00249.pdf

跟著要去找法案異動的時候發現 http://ly.g0v.tw/bills/1554G4442 or http://ly.g0v.tw/bills/1554G4442-8 都找不到資料

相關討論： http://logbot.g0v.tw/channel/g0v.tw/2015-01-10#53

**Comment by kiang** [comment]
http://lci.ly.gov.tw/LyLCEW/agenda1/02/pdf/08/06/14/LCEWA01_080614_00008.pdf

對應的 http://ly.g0v.tw/bills/246L17287 也是找不到

**Comment by kiang** [comment]
http://logbot.g0v.tw/channel/g0v.tw/2015-01-13#81

johnny: 關係文書有：
http://misq.ly.gov.tw/MISQ/IQuery/misq5000QueryBillDetail.action?billNo=1031205070200200
ttsmotions 也有：
http://lis.ly.gov.tw/lgcgi/ttsweb?@@B194F2C1C1C377B5C563
但api.ly還沒有

**Comment by clkao** [comment]
fixed in api.ly.
